// import { ITos, ILogout } from './ReducerType';
// import { ITicker } from '@/store/reducers/ticker';
// import { ILocales } from '@/store/reducers/locales';
// import { IActiveContracts } from '@/store/reducers/activeContracts';
// import { ISocket } from '@/store/reducers/socket';
// import { IExecReportResponse } from '@/store/reducers/execReportResponse';
// import { IChartData } from '@/store/reducers/chartData';
// import { IAccountInfoResponse } from '@/store/reducers/accountInfoResponse';
// import { IAccount } from '@/store/reducers/account';
// import { IAuth } from '@/store/reducers/auth';
// import { ICaptcha } from '@/store/reducers/captcha';
// import { ITerms } from '@/store/reducers/terms';
// import { IQueryDealQuoteResponse } from '@/store/reducers/queryDealQuoteResponse';
// import { IExecTrade } from '@/store/reducers/exectrade';
// import { IPlaceOrderInfo } from '@/store/reducers/placeOrderInfo';
// import { IRetrieveTransactionsResponse } from '@/store/reducers/retrieveTransactionsResponse';
// import { INavigation } from './navigation';
//
// export interface IaLLMapState {
//     locales: ILocales;
//     account: IAccount;
//     logoutStatus: ILogout;
//     ticker: ITicker;
//     tos: ITos;
//     terms: ITerms;
//     socket: ISocket;
//     navigation: INavigation;
//     activeContracts: IActiveContracts;
//     execReportResponse: IExecReportResponse;
//     chartData: IChartData;
//     accountInfoResponse: IAccountInfoResponse;
//     auth: IAuth;
//     captcha: ICaptcha;
//     queryDealQuoteResponse: IQueryDealQuoteResponse;
//     exectrade: IExecTrade;
//     placeOrderInfo: IPlaceOrderInfo;
//     retrieveTransactionsResponse: IRetrieveTransactionsResponse;
//     routing: any;
// };
